// Hand-picked curated playlist themes. Each entry maps to a YouTube Music
// search query whose top result is expected to be a large (>=40 track)
// editorial or community playlist. The resolver in /api/playlists/catalog
// filters candidates by trackCount >= MIN_TRACKS so we only surface sets
// that meet the quality floor.

export const MIN_TRACKS = 40;

export type CatalogCategory = "mood" | "era" | "vibe" | "genre";

export interface CatalogEntry {
  slug: string;
  title: string;
  subtitle: string;
  category: CatalogCategory;
  searchQuery: string;
  featured?: boolean;
  tags: string[];
  aliases?: string[];
  requiredTerms?: string[];
  preferredTerms?: string[];
  excludedTerms?: string[];
  minTracks?: number;
  idealTrackRange?: [number, number];
}

export const CURATED_CATALOG: CatalogEntry[] = [
  // ═══ Mood ═══
  {
    slug: "happy-days",
    title: "Happy Days",
    subtitle: "Uplifting hits to move the room",
    category: "mood",
    searchQuery: "feel good happy hits playlist",
    featured: true,
    tags: ["happy", "upbeat", "mood", "happy days", "feel good"],
    preferredTerms: ["happy", "feel good", "upbeat", "sunshine", "good mood"],
    excludedTerms: ["sad", "heartbreak", "cry"],
    idealTrackRange: [35, 120],
  },
  {
    slug: "sad-bangers",
    title: "Sad Bangers",
    subtitle: "Big feelings, bigger choruses",
    category: "mood",
    searchQuery: "sad songs playlist",
    tags: ["sad", "emotional", "mood"],
    preferredTerms: ["sad", "cry", "emotional", "heartbreak", "melancholy"],
    excludedTerms: ["happy", "workout", "party"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "focus-flow",
    title: "Focus Flow",
    subtitle: "Deep work, low friction",
    category: "mood",
    searchQuery: "deep focus instrumental playlist",
    featured: true,
    tags: ["focus", "work", "instrumental"],
    preferredTerms: ["focus", "deep focus", "instrumental", "study", "concentration"],
    excludedTerms: ["party", "workout", "lyrics heavy"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "chill-vibes",
    title: "Chill Vibes",
    subtitle: "Easy listening, zero pressure",
    category: "mood",
    searchQuery: "chill vibes playlist",
    tags: ["chill", "relax", "mood"],
    preferredTerms: ["chill", "relax", "laid back", "easy listening"],
    excludedTerms: ["hardcore", "rage", "workout"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "midnight-cruise",
    title: "Midnight Cruise",
    subtitle: "Streetlights, synth haze, and slow-burn momentum",
    category: "mood",
    searchQuery: "midnight drive playlist",
    featured: true,
    tags: ["midnight", "night drive", "roadtrip", "mood"],
    preferredTerms: ["midnight", "night drive", "late night", "drive", "nocturnal"],
    excludedTerms: ["kids", "party", "morning"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "rage-mode",
    title: "Rage Mode",
    subtitle: "High-octane workout & pregame",
    category: "mood",
    searchQuery: "workout hype playlist",
    tags: ["workout", "energy", "hype"],
    preferredTerms: ["workout", "hype", "gym", "energy", "beast mode"],
    excludedTerms: ["sleep", "sad", "acoustic"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "heartbreak",
    title: "Heartbreak",
    subtitle: "Soundtrack for the after-hours",
    category: "mood",
    searchQuery: "heartbreak songs playlist",
    tags: ["sad", "breakup", "mood"],
    preferredTerms: ["heartbreak", "breakup", "sad", "after hours"],
    excludedTerms: ["happy", "party", "kids"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "rainy-day",
    title: "Rainy Day",
    subtitle: "Grey windows, warm speakers",
    category: "mood",
    searchQuery: "rainy day playlist",
    tags: ["calm", "rain", "mood"],
    preferredTerms: ["rainy day", "rain", "grey", "calm", "overcast"],
    excludedTerms: ["workout", "festival", "party"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "soft-landing",
    title: "Soft Landing",
    subtitle: "Gentle textures for slowing the pulse",
    category: "mood",
    searchQuery: "soft acoustic chill playlist",
    tags: ["soft", "calm", "gentle", "mood"],
    preferredTerms: ["soft", "acoustic", "gentle", "calm", "quiet"],
    excludedTerms: ["edm", "trap", "metal"],
    idealTrackRange: [40, 85],
  },
  {
    slug: "velvet-weather",
    title: "Velvet Weather",
    subtitle: "Soulful warmth for overcast afternoons",
    category: "mood",
    searchQuery: "smooth soul chill playlist",
    tags: ["soul", "warm", "overcast", "mood"],
    preferredTerms: ["smooth soul", "soul", "warm", "chill", "velvet"],
    excludedTerms: ["hard rock", "edm", "festival"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "neon-focus",
    title: "Neon Focus",
    subtitle: "Electronic momentum without distraction",
    category: "mood",
    searchQuery: "focus electronic playlist",
    tags: ["focus", "electronic", "mood"],
    preferredTerms: ["focus", "electronic", "instrumental", "minimal", "neon"],
    excludedTerms: ["party", "big room", "festival"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "sunrise-reset",
    title: "Sunrise Reset",
    subtitle: "A clean start with light in the speakers",
    category: "mood",
    searchQuery: "morning reset playlist",
    tags: ["morning", "reset", "uplifting", "mood"],
    preferredTerms: ["morning", "sunrise", "reset", "uplifting", "fresh start"],
    excludedTerms: ["rage", "midnight", "party"],
    idealTrackRange: [40, 95],
  },

  // ═══ Era ═══
  {
    slug: "60s-soul",
    title: "60's Soul",
    subtitle: "Deep grooves, brass lifts, and timeless voices",
    category: "era",
    searchQuery: "60s soul essentials playlist",
    tags: ["60s", "soul", "era"],
    requiredTerms: ["60", "soul"],
    preferredTerms: ["motown", "stax", "soul", "1960s"],
    excludedTerms: ["2010", "edm", "trap"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "70s-classics",
    title: "70's Classics",
    subtitle: "Arena rock, funk, and soft-rock staples",
    category: "era",
    searchQuery: "70s rock classics playlist",
    tags: ["70s", "classic-rock", "era"],
    requiredTerms: ["70", "rock"],
    preferredTerms: ["classic rock", "70s", "arena", "vintage"],
    excludedTerms: ["2000", "trap", "2024"],
    idealTrackRange: [40, 110],
  },
  {
    slug: "80s-power-pop",
    title: "80's Power Pop",
    subtitle: "Synths, hair, and stadium hooks",
    category: "era",
    searchQuery: "80s pop hits playlist",
    featured: true,
    tags: ["80s", "pop", "era"],
    requiredTerms: ["80", "pop"],
    preferredTerms: ["80s", "synth", "power pop", "retro"],
    excludedTerms: ["2010", "2020", "drill"],
    idealTrackRange: [40, 110],
  },
  {
    slug: "90s-hiphop",
    title: "90's HipHop",
    subtitle: "Golden era boom-bap and West Coast cuts",
    category: "era",
    searchQuery: "90s hip hop classics playlist",
    featured: true,
    tags: ["90s", "hip-hop", "era"],
    aliases: ["90s hip hop", "golden era hip hop"],
    requiredTerms: ["90", "hip hop"],
    preferredTerms: ["golden era", "boom bap", "old school", "west coast", "east coast"],
    excludedTerms: ["trap", "drill", "2024", "new rap"],
    idealTrackRange: [40, 120],
  },
  {
    slug: "2000s-throwbacks",
    title: "2000's Throwbacks",
    subtitle: "Y2K radio, emo, and crunk anthems",
    category: "era",
    searchQuery: "2000s throwback hits playlist",
    tags: ["2000s", "throwback", "era"],
    requiredTerms: ["2000"],
    preferredTerms: ["throwback", "2000s", "y2k", "nostalgia"],
    excludedTerms: ["80s", "90s", "2024"],
    idealTrackRange: [40, 110],
  },
  {
    slug: "2010s-hits",
    title: "2010's Hits",
    subtitle: "Streaming-era pop and indie crossovers",
    category: "era",
    searchQuery: "2010s hits playlist",
    tags: ["2010s", "pop", "era"],
    requiredTerms: ["2010"],
    preferredTerms: ["2010s", "hits", "pop", "streaming era"],
    excludedTerms: ["80s", "90s", "2024"],
    idealTrackRange: [40, 110],
  },
  {
    slug: "90s-rnb",
    title: "90's R&B",
    subtitle: "Slow jams, hooks, and velvet harmonies",
    category: "era",
    searchQuery: "90s r&b playlist",
    tags: ["90s", "r&b", "era"],
    requiredTerms: ["90", "r b"],
    preferredTerms: ["slow jams", "90s", "r&b", "quiet storm"],
    excludedTerms: ["trap soul", "2024"],
    idealTrackRange: [35, 110],
  },
  {
    slug: "80s-new-wave",
    title: "80's New Wave",
    subtitle: "Synth lines, sharp jackets, and nocturnal hooks",
    category: "era",
    searchQuery: "80s new wave playlist",
    tags: ["80s", "new wave", "era"],
    requiredTerms: ["80", "wave"],
    preferredTerms: ["new wave", "synth", "post punk", "80s"],
    excludedTerms: ["2010", "edm", "trap"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "2000s-emo",
    title: "2000's Emo",
    subtitle: "Catharsis, distortion, and chorus-sized feelings",
    category: "era",
    searchQuery: "2000s emo playlist",
    tags: ["2000s", "emo", "era"],
    requiredTerms: ["2000", "emo"],
    preferredTerms: ["emo", "pop punk", "post hardcore", "2000s"],
    excludedTerms: ["trap", "edm", "country"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "blog-era-indie",
    title: "Blog Era Indie",
    subtitle: "Tumblr glow, festival tees, and alt-pop lift",
    category: "era",
    searchQuery: "2000s indie playlist",
    tags: ["2000s", "indie", "blog era", "era"],
    requiredTerms: ["2000", "indie"],
    preferredTerms: ["blog era", "indie", "2000s", "alternative"],
    excludedTerms: ["trap", "drill", "kpop"],
    idealTrackRange: [40, 90],
  },

  // ═══ Vibe / Scene ═══
  {
    slug: "midnight-roadtrip",
    title: "Midnight Roadtrip",
    subtitle: "Empty highways and moody synths",
    category: "vibe",
    searchQuery: "late night driving playlist",
    featured: true,
    tags: ["road", "night", "vibe"],
    aliases: ["late night drive", "night drive", "roadtrip"],
    preferredTerms: ["midnight", "late night", "night drive", "driving", "roadtrip", "neon"],
    excludedTerms: ["workout", "kids", "party games"],
    idealTrackRange: [30, 100],
  },
  {
    slug: "garage-bands",
    title: "Garage Bands",
    subtitle: "Messy amps, basement sweat, and live-wire hooks",
    category: "vibe",
    searchQuery: "garage rock playlist",
    featured: true,
    tags: ["garage bands", "garage rock", "raw", "vibe"],
    requiredTerms: ["garage"],
    preferredTerms: ["garage rock", "raw", "fuzz", "basement", "lo fi"],
    excludedTerms: ["soft rock", "pop ballads"],
    idealTrackRange: [30, 100],
  },
  {
    slug: "sunset-drives",
    title: "Sunset Drives",
    subtitle: "Golden hour on open road",
    category: "vibe",
    searchQuery: "sunset driving playlist",
    tags: ["sunset", "road", "vibe"],
    preferredTerms: ["sunset", "driving", "golden hour", "road"],
    excludedTerms: ["workout", "kids", "rage"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "coffee-shop",
    title: "Coffee Shop",
    subtitle: "Acoustic textures and quiet conversation",
    category: "vibe",
    searchQuery: "coffee shop acoustic playlist",
    tags: ["acoustic", "cafe", "vibe"],
    preferredTerms: ["coffee shop", "acoustic", "cafe", "folk", "indie"],
    excludedTerms: ["metal", "festival", "hardstyle"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "house-party",
    title: "House Party",
    subtitle: "Floor-filler energy all night",
    category: "vibe",
    searchQuery: "house party hits playlist",
    tags: ["party", "dance", "vibe"],
    preferredTerms: ["house party", "party", "hits", "dance"],
    excludedTerms: ["sleep", "focus", "sad"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "morning-run",
    title: "Morning Run",
    subtitle: "BPM-locked for steady cadence",
    category: "vibe",
    searchQuery: "running workout playlist",
    tags: ["run", "workout", "vibe"],
    preferredTerms: ["running", "workout", "run", "cardio"],
    excludedTerms: ["sleep", "slow", "acoustic"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "dinner-jazz",
    title: "Dinner Jazz",
    subtitle: "Mid-tempo standards and modern fusion",
    category: "vibe",
    searchQuery: "dinner jazz playlist",
    tags: ["jazz", "dinner", "vibe"],
    preferredTerms: ["dinner jazz", "jazz", "evening", "cocktail"],
    excludedTerms: ["metal", "drill", "festival"],
    idealTrackRange: [40, 85],
  },
  {
    slug: "study-session",
    title: "Study Session",
    subtitle: "Lo-fi and ambient for long focus blocks",
    category: "vibe",
    searchQuery: "lofi study playlist",
    tags: ["study", "lofi", "vibe"],
    preferredTerms: ["study", "lofi", "focus", "beats"],
    excludedTerms: ["party", "rage", "lyrics heavy"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "beach-bonfire",
    title: "Beach Bonfire",
    subtitle: "Warm harmonies after the sun drops",
    category: "vibe",
    searchQuery: "beach bonfire playlist",
    tags: ["beach", "summer", "vibe"],
    preferredTerms: ["beach", "bonfire", "summer", "warm night"],
    excludedTerms: ["metal", "drill", "gym"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "desert-motel",
    title: "Desert Motel",
    subtitle: "Dusty grooves and sunburnt psych edges",
    category: "vibe",
    searchQuery: "desert rock playlist",
    tags: ["desert", "psych", "road", "vibe"],
    preferredTerms: ["desert rock", "psych", "dusty", "road"],
    excludedTerms: ["dance pop", "kids", "workout"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "neon-skyline",
    title: "Neon Skyline",
    subtitle: "Glass towers, wet streets, and city-night pulse",
    category: "vibe",
    searchQuery: "night city playlist",
    tags: ["city", "night", "neon", "vibe"],
    preferredTerms: ["night", "city", "neon", "after dark"],
    excludedTerms: ["morning", "kids", "country"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "backyard-static",
    title: "Backyard Static",
    subtitle: "Loose guitars and warm-weather fuzz",
    category: "vibe",
    searchQuery: "indie garage summer playlist",
    tags: ["backyard", "garage", "summer", "vibe"],
    preferredTerms: ["garage", "summer", "indie", "backyard"],
    excludedTerms: ["ballad", "orchestral", "sleep"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "moonlit-disco",
    title: "Moonlit Disco",
    subtitle: "Mirrorball rhythm after midnight",
    category: "vibe",
    searchQuery: "nu disco playlist",
    tags: ["disco", "night", "dance", "vibe"],
    preferredTerms: ["nu disco", "disco", "night", "dance"],
    excludedTerms: ["metal", "drill", "acoustic"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "window-seat",
    title: "Window Seat",
    subtitle: "Cloudline calm for long-distance thinking",
    category: "vibe",
    searchQuery: "travel chill playlist",
    tags: ["travel", "airplane", "calm", "vibe"],
    preferredTerms: ["travel", "chill", "window seat", "flight"],
    excludedTerms: ["party", "festival", "workout"],
    idealTrackRange: [40, 95],
  },

  // ═══ Genre ═══
  {
    slug: "indie-rock",
    title: "Indie Rock",
    subtitle: "Modern indie rock & pop anthems",
    category: "genre",
    searchQuery: "indie rock essentials playlist",
    featured: true,
    tags: ["indie", "indie rock", "rock", "genre"],
    requiredTerms: ["indie", "rock"],
    preferredTerms: ["indie rock", "anthem", "alternative", "guitar"],
    excludedTerms: ["lofi beats", "hip hop", "rap"],
    idealTrackRange: [40, 140],
  },
  {
    slug: "pop-princess",
    title: "Pop Princess",
    subtitle: "Top 40 bops and diva moments",
    category: "genre",
    searchQuery: "pop hits playlist",
    tags: ["pop", "genre"],
    preferredTerms: ["pop", "hits", "diva", "mainstream"],
    excludedTerms: ["metal", "drill", "ambient"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "rnb-slow-jams",
    title: "R&B Slow Jams",
    subtitle: "Late-night grooves and quiet storms",
    category: "genre",
    searchQuery: "rnb slow jams playlist",
    tags: ["rnb", "slow", "genre"],
    preferredTerms: ["r&b", "slow jams", "quiet storm", "soul"],
    excludedTerms: ["drill", "hardstyle", "metal"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "country-roads",
    title: "Country Roads",
    subtitle: "Modern country and alt-country cuts",
    category: "genre",
    searchQuery: "country hits playlist",
    tags: ["country", "genre"],
    requiredTerms: ["country"],
    preferredTerms: ["country", "americana", "roads", "southern"],
    excludedTerms: ["edm", "trap", "kpop"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "latin-heat",
    title: "Latin Heat",
    subtitle: "Reggaeton, Latin pop, and street classics",
    category: "genre",
    searchQuery: "latin hits playlist",
    tags: ["latin", "reggaeton", "genre"],
    requiredTerms: ["latin"],
    preferredTerms: ["latin", "reggaeton", "urbano", "hits"],
    excludedTerms: ["metal", "emo", "country"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "afrobeats-fire",
    title: "Afrobeats Fire",
    subtitle: "Lagos to the rest of the world",
    category: "genre",
    searchQuery: "afrobeats hits playlist",
    tags: ["afrobeats", "genre"],
    requiredTerms: ["afrobeats"],
    preferredTerms: ["afrobeats", "afropop", "dance", "lagos"],
    excludedTerms: ["metal", "drill", "country"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "kpop-essentials",
    title: "K-Pop Essentials",
    subtitle: "Group cuts and solo showcases",
    category: "genre",
    searchQuery: "kpop hits playlist",
    tags: ["kpop", "genre"],
    requiredTerms: ["kpop"],
    preferredTerms: ["k-pop", "hits", "groups", "idols"],
    excludedTerms: ["metal", "drill", "country"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "classic-rock",
    title: "Classic Rock",
    subtitle: "Guitar-forward arena staples",
    category: "genre",
    searchQuery: "classic rock hits playlist",
    tags: ["rock", "classic", "genre"],
    requiredTerms: ["rock"],
    preferredTerms: ["classic rock", "guitar", "anthem", "vintage"],
    excludedTerms: ["drill", "edm", "kpop"],
    idealTrackRange: [40, 110],
  },
  {
    slug: "edm-festival",
    title: "EDM Festival",
    subtitle: "Main-stage builds and drops",
    category: "genre",
    searchQuery: "edm festival hits playlist",
    tags: ["edm", "dance", "genre"],
    requiredTerms: ["edm"],
    preferredTerms: ["festival", "edm", "drops", "dance"],
    excludedTerms: ["acoustic", "country", "jazz"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "metal-essentials",
    title: "Metal Essentials",
    subtitle: "Riffs, speed, and atmosphere",
    category: "genre",
    searchQuery: "metal essentials playlist",
    tags: ["metal", "rock", "genre"],
    requiredTerms: ["metal"],
    preferredTerms: ["metal", "heavy", "riff", "hard rock"],
    excludedTerms: ["pop", "acoustic", "r&b"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "garage-rock",
    title: "Garage Rock",
    subtitle: "Loose, loud, and full of distortion",
    category: "genre",
    searchQuery: "garage rock essentials playlist",
    tags: ["garage", "garage bands", "rock", "genre"],
    requiredTerms: ["garage", "rock"],
    preferredTerms: ["garage rock", "raw", "fuzz", "lo fi"],
    excludedTerms: ["soft rock", "edm", "ballad"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "indie-folk",
    title: "Indie Folk",
    subtitle: "Acoustic edges and singalong choruses",
    category: "genre",
    searchQuery: "indie folk playlist",
    tags: ["indie folk", "folk", "genre"],
    requiredTerms: ["folk"],
    preferredTerms: ["indie folk", "acoustic", "singer songwriter", "rustic"],
    excludedTerms: ["edm", "metal", "drill"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "dream-pop",
    title: "Dream Pop",
    subtitle: "Shimmer, reverb, and floating hooks",
    category: "genre",
    searchQuery: "dream pop playlist",
    tags: ["dream pop", "shoegaze", "genre"],
    requiredTerms: ["dream", "pop"],
    preferredTerms: ["dream pop", "shimmer", "ethereal", "reverb"],
    excludedTerms: ["dance pop", "teen pop"],
    idealTrackRange: [30, 90],
  },
  {
    slug: "shoegaze-signals",
    title: "Shoegaze Signals",
    subtitle: "Blurred amps and sky-sized texture",
    category: "genre",
    searchQuery: "shoegaze essentials playlist",
    tags: ["shoegaze", "noise pop", "genre"],
    requiredTerms: ["shoegaze"],
    preferredTerms: ["shoegaze", "wall of sound", "reverb", "noise pop"],
    excludedTerms: ["dance pop", "trap", "kids"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "post-punk-wire",
    title: "Post-Punk Wire",
    subtitle: "Bass tension and angular momentum",
    category: "genre",
    searchQuery: "post punk playlist",
    tags: ["post-punk", "indie", "genre"],
    requiredTerms: ["post", "punk"],
    preferredTerms: ["post punk", "bass", "angular", "new wave"],
    excludedTerms: ["pop punk", "trap", "country"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "ambient-drift",
    title: "Ambient Drift",
    subtitle: "Long-form atmosphere and slow horizon motion",
    category: "genre",
    searchQuery: "ambient essentials playlist",
    tags: ["ambient", "drone", "genre"],
    requiredTerms: ["ambient"],
    preferredTerms: ["ambient", "drone", "atmospheric", "slow"],
    excludedTerms: ["party", "workout", "drill"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "bossa-nights",
    title: "Bossa Nights",
    subtitle: "Soft percussion and candlelit sway",
    category: "genre",
    searchQuery: "bossa nova playlist",
    tags: ["bossa nova", "brazil", "genre"],
    requiredTerms: ["bossa"],
    preferredTerms: ["bossa nova", "brazil", "soft", "sway"],
    excludedTerms: ["metal", "festival", "drill"],
    idealTrackRange: [40, 85],
  },
  {
    slug: "soul-revival",
    title: "Soul Revival",
    subtitle: "Modern grooves rooted in classic feeling",
    category: "genre",
    searchQuery: "neo soul playlist",
    tags: ["neo soul", "soul", "genre"],
    preferredTerms: ["neo soul", "soul", "groove", "slow jam", "r&b"],
    excludedTerms: ["hard rock", "metal"],
    idealTrackRange: [30, 90],
  },
  {
    slug: "funk-doctrine",
    title: "Funk Doctrine",
    subtitle: "Bass-led swagger and sharp-pocket rhythm",
    category: "genre",
    searchQuery: "funk essentials playlist",
    tags: ["funk", "groove", "genre"],
    requiredTerms: ["funk"],
    preferredTerms: ["funk", "groove", "bass", "rhythm"],
    excludedTerms: ["drill", "sad piano", "ambient"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "afro-house",
    title: "Afro House",
    subtitle: "Percussive lift for deep-floor momentum",
    category: "genre",
    searchQuery: "afro house playlist",
    tags: ["afro house", "house", "genre"],
    requiredTerms: ["house"],
    preferredTerms: ["afro house", "percussion", "deep house", "tribal"],
    excludedTerms: ["hip hop", "trap", "pop hits"],
    idealTrackRange: [25, 80],
  },
  {
    slug: "reggaeton-pulse",
    title: "Reggaeton Pulse",
    subtitle: "Perreo energy with arena-sized hooks",
    category: "genre",
    searchQuery: "reggaeton hits playlist",
    tags: ["reggaeton", "latin", "genre"],
    requiredTerms: ["reggaeton"],
    preferredTerms: ["reggaeton", "latin", "perreo", "hits"],
    excludedTerms: ["metal", "country", "ambient"],
    idealTrackRange: [40, 100],
  },
  {
    slug: "alt-country-nights",
    title: "Alt Country Nights",
    subtitle: "Road-worn songwriting and open-sky grit",
    category: "genre",
    searchQuery: "alt country playlist",
    tags: ["alt country", "americana", "genre"],
    requiredTerms: ["country"],
    preferredTerms: ["alt country", "americana", "road worn", "twang"],
    excludedTerms: ["edm", "kpop", "drill"],
    idealTrackRange: [40, 95],
  },
  {
    slug: "drill-pressure",
    title: "Drill Pressure",
    subtitle: "Dark low-end and razor-wire cadence",
    category: "genre",
    searchQuery: "drill playlist",
    tags: ["drill", "rap", "genre"],
    requiredTerms: ["drill"],
    preferredTerms: ["drill", "dark", "808", "pressure"],
    excludedTerms: ["happy", "acoustic", "country"],
    idealTrackRange: [40, 90],
  },
  {
    slug: "jazz-house",
    title: "Jazz House",
    subtitle: "Club propulsion with live-musician nerve",
    category: "genre",
    searchQuery: "jazz house playlist",
    tags: ["jazz house", "house", "genre"],
    requiredTerms: ["house"],
    preferredTerms: ["jazz house", "jazz", "house", "club"],
    excludedTerms: ["metal", "country", "drill"],
    idealTrackRange: [40, 85],
  },
];

export const CATALOG_CATEGORIES: Array<{ id: CatalogCategory; label: string }> = [
  { id: "mood", label: "Mood" },
  { id: "era", label: "Era" },
  { id: "vibe", label: "Vibe" },
  { id: "genre", label: "Genre" },
];
