import type { CatalogEntry, CatalogCategory } from "@/lib/curated-catalog";

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function entry(
  title: string,
  subtitle: string,
  category: CatalogCategory,
  searchQuery: string,
  tags: string[] = []
): CatalogEntry {
  return { slug: slug(title), title, subtitle, category, searchQuery, tags };
}

// ─── Moods ────────────────────────────────────────────────────────────────────

const MOODS: CatalogEntry[] = [
  entry("Happy Days", "Bright, easy serotonin", "mood", "happy feel good playlist", ["happy", "upbeat", "feel good"]),
  entry("Good Vibes Only", "Pure positivity, zero filler", "mood", "good vibes only playlist", ["positive", "happy"]),
  entry("Euphoria", "Peak energy, peak joy", "mood", "euphoria happy songs playlist", ["euphoric", "uplifting"]),
  entry("Sunshine Hits", "Songs that feel like sunlight", "mood", "sunshine uplifting songs playlist", ["sunny", "bright"]),
  entry("Feel Good Friday", "End-of-week energy drop", "mood", "feel good friday playlist", ["feel good", "weekend"]),
  entry("Instant Mood Lift", "Fast-acting sonic serotonin", "mood", "instant mood booster playlist", ["upbeat", "energetic"]),

  entry("Sad Hours", "Songs for the hard nights", "mood", "sad songs playlist", ["sad", "emotional"]),
  entry("Heartbreak Hotel", "Post-breakup listening ward", "mood", "heartbreak songs playlist", ["heartbreak", "sad love"]),
  entry("Blue Midnight", "Quiet pain, slow tempo", "mood", "blue sad midnight playlist", ["melancholy", "slow"]),
  entry("Crying in the Car", "Let it all out", "mood", "crying songs emotional playlist", ["emotional", "sad"]),
  entry("Melancholy Signal", "Bittersweet and beautiful", "mood", "melancholy bittersweet songs", ["melancholy", "introspective"]),
  entry("Rainy Window", "Grey skies, warm feelings", "mood", "rainy day sad songs playlist", ["rainy", "contemplative"]),

  entry("Chill Mode", "Zero stress, full drift", "mood", "chill vibes playlist", ["chill", "relaxed"]),
  entry("Sunday Slow Down", "Gentle pace, no rush", "mood", "sunday chill playlist", ["chill", "sunday"]),
  entry("Afternoon Drift", "Lazy afternoon energy", "mood", "afternoon chill playlist", ["chill", "lazy"]),
  entry("Mellow Gold", "Soft and golden", "mood", "mellow chill playlist", ["mellow", "soft"]),
  entry("Low Key Flex", "Laid back but still cool", "mood", "low key chill playlist", ["chill", "smooth"]),

  entry("Hype Mode", "Maximum energy activation", "mood", "hype high energy playlist", ["hype", "energetic", "pump up"]),
  entry("Pump Up", "Pre-game fuel injection", "mood", "pump up songs playlist", ["pump up", "motivational"]),
  entry("Adrenaline Rush", "Unstoppable momentum", "mood", "adrenaline rush high energy playlist", ["adrenaline", "intense"]),
  entry("Beast Mode", "Train like you mean it", "mood", "beast mode workout playlist", ["beast mode", "intense"]),

  entry("Romantic Evening", "Candlelight and close harmony", "mood", "romantic evening songs playlist", ["romantic", "love"]),
  entry("Love Songs", "All the feelings, all the time", "mood", "love songs playlist", ["love", "romance"]),
  entry("Slow Dance", "Pull someone close", "mood", "slow dance songs playlist", ["slow dance", "romantic"]),
  entry("Late Night Romance", "Dim lights, soft music", "mood", "late night romantic playlist", ["romantic", "late night"]),

  entry("Deep Nostalgia", "Memories in audio form", "mood", "nostalgia throwback playlist", ["nostalgic", "memories"]),
  entry("Throwback Feels", "Takes you straight back", "mood", "throwback hits playlist", ["throwback", "nostalgic"]),
  entry("Old School Vibes", "When music felt different", "mood", "old school vibes playlist", ["old school", "retro"]),

  entry("Angry Hours", "Channeled frustration", "mood", "angry songs playlist", ["angry", "intense", "aggressive"]),
  entry("Catharsis", "Feel it all and release", "mood", "cathartic emotional songs", ["cathartic", "release"]),
  entry("Rage Fuel", "Maximum intensity output", "mood", "rage fuel angry songs", ["rage", "intense"]),

  entry("Dark Frequencies", "Brooding, low-lit energy", "mood", "dark moody songs playlist", ["dark", "brooding"]),
  entry("Midnight Thoughts", "Late night introspection", "mood", "midnight thoughts playlist", ["midnight", "introspective"]),
  entry("Noir Signal", "Shadows and slow tempos", "mood", "dark noir songs playlist", ["dark", "noir", "moody"]),

  entry("Hopeful", "Light at the end", "mood", "hopeful uplifting songs playlist", ["hopeful", "optimistic"]),
  entry("New Beginnings", "Fresh start energy", "mood", "new beginnings songs playlist", ["hopeful", "new start"]),
  entry("Determined", "Eyes forward, no doubt", "mood", "determined motivational songs", ["determined", "motivated"]),
  entry("Confidence Boost", "Walk taller with this on", "mood", "confidence boost songs playlist", ["confident", "empowering"]),

  entry("Dreamy State", "Half-awake and floating", "mood", "dreamy songs playlist", ["dreamy", "ethereal"]),
  entry("Daydream", "Soft focus, soft sound", "mood", "daydream songs playlist", ["dreamy", "soft"]),
  entry("Hazy Afternoon", "Warm and unfocused", "mood", "hazy afternoon songs playlist", ["hazy", "mellow"]),

  entry("Peaceful Mind", "Still water, clear air", "mood", "peaceful calming songs playlist", ["peaceful", "calm"]),
  entry("Zen State", "Presence over urgency", "mood", "zen calm meditation music", ["zen", "calm"]),
  entry("Gratitude", "Slow appreciation", "mood", "gratitude thankful songs playlist", ["gratitude", "positive"]),

  entry("Mysterious", "Something just under the surface", "mood", "mysterious dark songs playlist", ["mysterious", "eerie"]),
  entry("Tense Atmosphere", "Edge-of-seat sound design", "mood", "tense atmospheric songs", ["tense", "suspense"]),
  entry("Introspective", "Turn inward, sit with it", "mood", "introspective songs playlist", ["introspective", "thoughtful"]),
  entry("Spiritual", "Something larger than self", "mood", "spiritual songs playlist", ["spiritual", "soulful"]),
];

// ─── Genres ───────────────────────────────────────────────────────────────────

const GENRES: CatalogEntry[] = [
  entry("Indie Rock", "Guitars, hooks, and attitude", "genre", "indie rock essentials playlist", ["indie", "rock"]),
  entry("Indie Pop", "Bright indie with pop shine", "genre", "indie pop playlist", ["indie pop"]),
  entry("Indie Folk", "Soft-spoken and story-driven", "genre", "indie folk playlist", ["indie folk"]),
  entry("Garage Rock", "Raw, scrappy, loud", "genre", "garage rock playlist", ["garage rock"]),
  entry("Surf Rock", "Sun-drenched reverb waves", "genre", "surf rock playlist", ["surf rock"]),
  entry("Psychedelic Rock", "Expanded minds, expanded sounds", "genre", "psychedelic rock playlist", ["psychedelic"]),
  entry("Classic Rock", "Timeless electric authority", "genre", "classic rock playlist", ["classic rock"]),
  entry("Hard Rock", "Heavy guitar energy", "genre", "hard rock playlist", ["hard rock"]),
  entry("Heavy Metal", "Down-tuned dominance", "genre", "heavy metal playlist", ["metal", "heavy"]),
  entry("Thrash Metal", "Speed and aggression", "genre", "thrash metal playlist", ["thrash", "metal"]),
  entry("Doom Metal", "Slow, crushing, massive", "genre", "doom metal playlist", ["doom metal"]),
  entry("Black Metal", "Freezing and raw", "genre", "black metal playlist", ["black metal"]),
  entry("Prog Rock", "Technical complexity, epic scale", "genre", "progressive rock playlist", ["prog rock"]),
  entry("Post-Rock", "Instrumental builds to the sky", "genre", "post rock playlist", ["post rock"]),
  entry("Math Rock", "Odd time signatures, clean tones", "genre", "math rock playlist", ["math rock"]),
  entry("Emo", "Vulnerability amplified", "genre", "emo playlist", ["emo"]),
  entry("Screamo", "Raw and ragged catharsis", "genre", "screamo playlist", ["screamo", "emo"]),
  entry("Punk", "Short, fast, defiant", "genre", "punk rock playlist", ["punk"]),
  entry("Post-Punk", "Cold and angular", "genre", "post punk playlist", ["post punk"]),
  entry("New Wave", "Electronic meets punk energy", "genre", "new wave playlist", ["new wave"]),
  entry("Alternative Rock", "Off-centre, undeniable", "genre", "alternative rock playlist", ["alternative"]),
  entry("Grunge", "Seattle distortion cloud", "genre", "grunge playlist", ["grunge"]),
  entry("Shoegaze", "Walls of layered reverb", "genre", "shoegaze playlist", ["shoegaze"]),
  entry("Dream Pop", "Hazy shimmer and drift", "genre", "dream pop playlist", ["dream pop"]),
  entry("Noise Rock", "Abrasive and intentional", "genre", "noise rock playlist", ["noise rock"]),
  entry("Krautrock", "German hypnotic groove", "genre", "krautrock playlist", ["krautrock"]),

  entry("Soul", "Warmth from the chest", "genre", "soul music playlist", ["soul"]),
  entry("Classic Soul", "Motown and golden-era voices", "genre", "classic soul playlist", ["classic soul"]),
  entry("Neo Soul", "Modern soul depth", "genre", "neo soul playlist", ["neo soul"]),
  entry("Funk", "The groove that locks you in", "genre", "funk playlist", ["funk"]),
  entry("R&B", "Rhythm, feeling, presence", "genre", "r&b playlist", ["r&b"]),
  entry("Contemporary R&B", "Modern textured R&B", "genre", "contemporary r&b playlist", ["modern r&b"]),
  entry("Quiet Storm", "Slow, smooth, late night R&B", "genre", "quiet storm r&b playlist", ["quiet storm"]),
  entry("Gospel", "Devotion in full voice", "genre", "gospel music playlist", ["gospel"]),
  entry("Blues", "Twelve bars of truth", "genre", "blues music playlist", ["blues"]),
  entry("Delta Blues", "Raw and ancient Delta sound", "genre", "delta blues playlist", ["delta blues"]),
  entry("Chicago Blues", "Electric city blues", "genre", "chicago blues playlist", ["chicago blues"]),
  entry("Disco", "The floor is yours", "genre", "disco playlist", ["disco"]),
  entry("Nu Disco", "Disco reborn in the modern era", "genre", "nu disco playlist", ["nu disco"]),
  entry("Funk Soul", "Groove-forward fusion", "genre", "funk soul playlist", ["funk", "soul"]),

  entry("Hip-Hop", "Bars over beats", "genre", "hip hop playlist", ["hip hop", "rap"]),
  entry("Boom Bap", "Classic sample-based knock", "genre", "boom bap hip hop playlist", ["boom bap"]),
  entry("Golden Era Hip-Hop", "90s peak rap craft", "genre", "golden era hip hop playlist", ["golden era"]),
  entry("Underground Hip-Hop", "Left-field lyricism", "genre", "underground hip hop playlist", ["underground rap"]),
  entry("Trap", "808s and hi-hat rolls", "genre", "trap music playlist", ["trap"]),
  entry("Drill", "Menacing and minimal", "genre", "drill music playlist", ["drill"]),
  entry("Lo-Fi Hip-Hop", "Dusty loops for quiet hours", "genre", "lofi hip hop playlist", ["lofi", "beats"]),
  entry("Jazz Rap", "Intellectual bars, jazz chords", "genre", "jazz rap playlist", ["jazz rap"]),
  entry("Conscious Rap", "Lyricism with purpose", "genre", "conscious rap playlist", ["conscious rap"]),
  entry("West Coast Rap", "Sun, bass, lowriders", "genre", "west coast rap playlist", ["west coast rap"]),
  entry("East Coast Rap", "New York state of mind", "genre", "east coast rap playlist", ["east coast rap"]),
  entry("Southern Hip-Hop", "Crunk, chopped, and screwed", "genre", "southern hip hop playlist", ["southern rap"]),

  entry("House", "Four-on-the-floor foundation", "genre", "house music playlist", ["house"]),
  entry("Deep House", "Warm basement groove", "genre", "deep house playlist", ["deep house"]),
  entry("Tech House", "Driving and functional", "genre", "tech house playlist", ["tech house"]),
  entry("Acid House", "303 and pure ecstasy", "genre", "acid house playlist", ["acid house"]),
  entry("Garage House", "Chicago and New York roots", "genre", "garage house playlist", ["garage house"]),
  entry("Afro House", "African percussion, club floor", "genre", "afro house playlist", ["afro house"]),
  entry("Techno", "Detroit machinery and discipline", "genre", "techno playlist", ["techno"]),
  entry("Trance", "Build, drop, ascend", "genre", "trance music playlist", ["trance"]),
  entry("Drum & Bass", "170 BPM split-second breaks", "genre", "drum and bass playlist", ["drum and bass", "dnb"]),
  entry("Jungle", "Amen break, raw energy", "genre", "jungle music playlist", ["jungle"]),
  entry("Dubstep", "Heavy bass oscillation", "genre", "dubstep playlist", ["dubstep"]),
  entry("Grime", "UK garage's angular cousin", "genre", "grime music playlist", ["grime"]),
  entry("UK Garage", "2-step shuffle from London", "genre", "uk garage playlist", ["uk garage"]),
  entry("Ambient", "Atmosphere over rhythm", "genre", "ambient music playlist", ["ambient"]),
  entry("IDM", "Intelligent dance and broken beats", "genre", "idm intelligent dance music playlist", ["idm"]),
  entry("Synthwave", "Neon-soaked analog revival", "genre", "synthwave playlist", ["synthwave"]),
  entry("Vaporwave", "Aesthetic and ironic nostalgia", "genre", "vaporwave playlist", ["vaporwave"]),
  entry("Chillwave", "Hazy lo-fi electronic drift", "genre", "chillwave playlist", ["chillwave"]),
  entry("Electronica", "Experimental electronic exploration", "genre", "electronica playlist", ["electronica"]),
  entry("EDM", "Festival-ready drops", "genre", "edm playlist", ["edm"]),

  entry("Jazz", "Improvisation and conversation", "genre", "jazz playlist", ["jazz"]),
  entry("Bebop", "Fast tempos, complex harmony", "genre", "bebop jazz playlist", ["bebop"]),
  entry("Cool Jazz", "Relaxed and refined", "genre", "cool jazz playlist", ["cool jazz"]),
  entry("Hard Bop", "Bluesy and soulful jazz", "genre", "hard bop jazz playlist", ["hard bop"]),
  entry("Modal Jazz", "Miles, Coltrane, open space", "genre", "modal jazz playlist", ["modal jazz"]),
  entry("Free Jazz", "Outside the changes", "genre", "free jazz playlist", ["free jazz"]),
  entry("Jazz Fusion", "Electric meets improvisation", "genre", "jazz fusion playlist", ["jazz fusion"]),
  entry("Smooth Jazz", "Easy and polished", "genre", "smooth jazz playlist", ["smooth jazz"]),
  entry("Latin Jazz", "Cuban rhythm and jazz harmony", "genre", "latin jazz playlist", ["latin jazz"]),
  entry("Bossa Nova", "Brazilian sway and whisper", "genre", "bossa nova playlist", ["bossa nova"]),

  entry("Pop", "Melodic hooks for everyone", "genre", "pop hits playlist", ["pop"]),
  entry("Indie Pop", "Pop with an independent edge", "genre", "indie pop playlist", ["indie pop"]),
  entry("Art Pop", "Experimental and melodic", "genre", "art pop playlist", ["art pop"]),
  entry("Synth Pop", "Polished electronic melodies", "genre", "synth pop playlist", ["synth pop"]),
  entry("Baroque Pop", "Orchestral and ornate", "genre", "baroque pop playlist", ["baroque pop"]),
  entry("Chamber Pop", "Strings and intimacy", "genre", "chamber pop playlist", ["chamber pop"]),
  entry("Dance Pop", "Melody meets the floor", "genre", "dance pop playlist", ["dance pop"]),
  entry("Power Pop", "Big hooks, bigger guitars", "genre", "power pop playlist", ["power pop"]),

  entry("Country", "Open roads and honest words", "genre", "country music playlist", ["country"]),
  entry("Outlaw Country", "Rough edges, no compromise", "genre", "outlaw country playlist", ["outlaw country"]),
  entry("Americana", "Roots, dust, and truth", "genre", "americana playlist", ["americana"]),
  entry("Bluegrass", "Acoustic speed and precision", "genre", "bluegrass playlist", ["bluegrass"]),
  entry("Folk", "Voice and story, nothing else", "genre", "folk music playlist", ["folk"]),
  entry("Contemporary Folk", "Modern folk sound", "genre", "contemporary folk playlist", ["folk"]),
  entry("Freak Folk", "Strange and acoustic", "genre", "freak folk playlist", ["freak folk"]),

  entry("Classical", "The canon and beyond", "genre", "classical music playlist", ["classical"]),
  entry("Baroque", "Counterpoint and clarity", "genre", "baroque music playlist", ["baroque"]),
  entry("Romantic Classical", "Emotion at orchestral scale", "genre", "romantic classical music playlist", ["romantic classical"]),
  entry("Modern Classical", "20th century and forward", "genre", "modern classical music playlist", ["modern classical"]),
  entry("Minimalist Classical", "Repetition and slow change", "genre", "minimalist classical playlist", ["minimalist"]),
  entry("Piano Essentials", "Keys and pure expression", "genre", "piano music playlist", ["piano"]),
  entry("String Quartet", "Four strings, infinite depth", "genre", "string quartet playlist", ["strings", "chamber"]),

  entry("Reggae", "Riddim and roots", "genre", "reggae playlist", ["reggae"]),
  entry("Roots Reggae", "Conscious and righteous", "genre", "roots reggae playlist", ["roots reggae"]),
  entry("Dancehall", "Kingston party frequency", "genre", "dancehall playlist", ["dancehall"]),
  entry("Ska", "Upstroke pulse", "genre", "ska music playlist", ["ska"]),
  entry("Dub", "Bass in the echo chamber", "genre", "dub music playlist", ["dub"]),

  entry("Afrobeats", "West African energy exported worldwide", "genre", "afrobeats playlist", ["afrobeats"]),
  entry("Afropop", "Melodic pan-African pop", "genre", "afropop playlist", ["afropop"]),
  entry("Highlife", "Ghanaian brass and swing", "genre", "highlife music playlist", ["highlife"]),
  entry("Amapiano", "South African log drum groove", "genre", "amapiano playlist", ["amapiano"]),
  entry("K-Pop", "Precision and spectacle", "genre", "kpop playlist", ["k-pop", "kpop"]),
  entry("K-Indie", "Seoul bedroom and cafe sounds", "genre", "k-indie playlist", ["k-indie"]),
  entry("City Pop", "Tokyo bubble-era glamour", "genre", "city pop playlist", ["city pop"]),
  entry("J-Pop", "Japanese melodic pop", "genre", "j-pop playlist", ["j-pop"]),
  entry("Latin Pop", "Romance in every chord", "genre", "latin pop playlist", ["latin pop"]),
  entry("Reggaeton", "Dembow pattern, global reach", "genre", "reggaeton playlist", ["reggaeton"]),
  entry("Salsa", "Brass, percussion, movement", "genre", "salsa music playlist", ["salsa"]),
  entry("Cumbia", "Colombian coastal pulse", "genre", "cumbia playlist", ["cumbia"]),
];

// ─── Eras ─────────────────────────────────────────────────────────────────────

const ERAS: CatalogEntry[] = [
  entry("50s Rock & Roll", "The birth of the electric age", "era", "1950s rock and roll playlist", ["50s"]),
  entry("60s Pop", "Beatles era brightness", "era", "1960s pop playlist", ["60s", "60s pop"]),
  entry("60s Soul", "Motown and Stax golden run", "era", "1960s soul playlist", ["60s soul"]),
  entry("60s Psychedelic", "Expanded consciousness, wide reverb", "era", "1960s psychedelic playlist", ["60s psychedelic"]),
  entry("60s Folk Revival", "Dylan, protest, acoustic truth", "era", "1960s folk playlist", ["60s folk"]),
  entry("70s Rock", "Album-side dominance", "era", "1970s rock playlist", ["70s rock"]),
  entry("70s Funk", "James Brown era groove", "era", "1970s funk playlist", ["70s funk"]),
  entry("70s Disco", "Mirror ball paradise", "era", "1970s disco playlist", ["70s disco"]),
  entry("70s Punk", "Three chords and fury", "era", "1970s punk playlist", ["70s punk"]),
  entry("70s Soul", "Philadelphia and beyond", "era", "1970s soul playlist", ["70s soul"]),
  entry("70s Singer-Songwriter", "Laurel Canyon and confessional", "era", "1970s singer songwriter playlist", ["70s folk"]),
  entry("80s Pop", "Big hooks, bigger hair", "era", "1980s pop playlist", ["80s pop"]),
  entry("80s Rock", "Power chords and arenas", "era", "1980s rock playlist", ["80s rock"]),
  entry("80s Metal", "Spandex and stadium solos", "era", "1980s heavy metal playlist", ["80s metal"]),
  entry("80s New Wave", "Synths and angular cool", "era", "1980s new wave playlist", ["80s new wave"]),
  entry("80s Hip-Hop", "Break beats and block parties", "era", "1980s hip hop playlist", ["80s hip hop"]),
  entry("80s R&B", "Smooth grooves and shoulder pads", "era", "1980s r&b playlist", ["80s r&b"]),
  entry("80s Electronic", "Roland boxes and MIDI everything", "era", "1980s electronic playlist", ["80s electronic"]),
  entry("90s Pop", "TRL peak, pure melody", "era", "1990s pop playlist", ["90s pop"]),
  entry("90s Rock", "Alternative radio dominance", "era", "1990s rock playlist", ["90s rock"]),
  entry("90s Grunge", "Seattle and distortion", "era", "1990s grunge playlist", ["90s grunge"]),
  entry("90s Alternative", "College radio gold", "era", "1990s alternative playlist", ["90s alternative"]),
  entry("90s Hip-Hop", "Golden era lyricism", "era", "1990s hip hop playlist", ["90s hip hop"]),
  entry("90s R&B", "Slow jams and multi-harmonies", "era", "1990s r&b playlist", ["90s r&b"]),
  entry("90s Dance", "Eurodance and club anthems", "era", "1990s dance playlist", ["90s dance"]),
  entry("90s Electronic", "Rave and jungle emergence", "era", "1990s electronic playlist", ["90s electronic"]),
  entry("90s Britpop", "Oasis, Blur, British invasion", "era", "1990s britpop playlist", ["britpop"]),
  entry("2000s Pop", "Pop princess and boy band era", "era", "2000s pop playlist", ["2000s pop"]),
  entry("2000s Indie", "Blog-era guitar explosion", "era", "2000s indie playlist", ["2000s indie"]),
  entry("2000s Hip-Hop", "Bling era, snap, ringtone rap", "era", "2000s hip hop playlist", ["2000s hip hop"]),
  entry("2000s Emo", "Eyeliner and catharsis", "era", "2000s emo playlist", ["2000s emo"]),
  entry("2000s R&B", "Usher, Beyoncé, neo-smooth", "era", "2000s r&b playlist", ["2000s r&b"]),
  entry("2000s Electronic", "Electro and microhouse", "era", "2000s electronic playlist", ["2000s electronic"]),
  entry("2000s Rock", "Post-grunge and nu-metal", "era", "2000s rock playlist", ["2000s rock"]),
  entry("2010s Pop", "Streaming-era hooks", "era", "2010s pop playlist", ["2010s pop"]),
  entry("2010s Hip-Hop", "Trap era takeover", "era", "2010s hip hop playlist", ["2010s hip hop"]),
  entry("2010s Indie", "Bedroom pop and festival indie", "era", "2010s indie playlist", ["2010s indie"]),
  entry("2010s R&B", "Alt-R&B and Frank Ocean era", "era", "2010s r&b playlist", ["2010s r&b"]),
  entry("2010s Electronic", "Future bass and tropical house", "era", "2010s electronic playlist", ["2010s electronic"]),
  entry("Early 2020s", "Post-pandemic pop and rap", "era", "early 2020s hits playlist", ["2020s"]),
];

// ─── Activities ───────────────────────────────────────────────────────────────

const ACTIVITIES: CatalogEntry[] = [
  entry("Morning Run", "Pace yourself into the day", "vibe", "morning run playlist", ["running", "morning"]),
  entry("Heavy Lifting", "Iron and raw power", "vibe", "heavy lifting gym playlist", ["lifting", "gym"]),
  entry("Cardio Burn", "Keep the heart rate up", "vibe", "cardio workout playlist", ["cardio"]),
  entry("HIIT Session", "Short bursts, full effort", "vibe", "hiit workout playlist", ["hiit", "workout"]),
  entry("Yoga Flow", "Breath-synced movement", "vibe", "yoga music playlist", ["yoga"]),
  entry("Meditation", "Space between the thoughts", "vibe", "meditation music playlist", ["meditation"]),
  entry("Stretching Session", "Ease in, ease out", "vibe", "stretching relaxing playlist", ["stretching"]),
  entry("Study Session", "Focus locked, distractions off", "vibe", "study music playlist", ["study"]),
  entry("Deep Work", "Flow state maintenance", "vibe", "deep work focus playlist", ["focus", "work"]),
  entry("Coding Session", "Headphones on, world off", "vibe", "coding focus playlist", ["coding", "focus"]),
  entry("Reading Companion", "Background for deep reading", "vibe", "reading background music playlist", ["reading"]),
  entry("Morning Coffee", "Gentle start to the day", "vibe", "morning coffee playlist", ["morning", "coffee"]),
  entry("Wake Up Call", "From bed to moving", "vibe", "wake up morning energy playlist", ["morning", "energetic"]),
  entry("Commute Soundtrack", "Transit time well spent", "vibe", "commute playlist", ["commute"]),
  entry("Road Trip", "Miles and playlists", "vibe", "road trip playlist", ["road trip", "driving"]),
  entry("Midnight Drive", "Empty roads, full volume", "vibe", "midnight drive playlist", ["midnight", "drive"]),
  entry("Late Night Drive", "City lights, open windows", "vibe", "late night drive playlist", ["late night", "drive"]),
  entry("Sunday Drive", "No destination, just motion", "vibe", "sunday drive playlist", ["sunday", "drive"]),
  entry("Dinner Party", "Food, friends, curated sound", "vibe", "dinner party playlist", ["dinner", "social"]),
  entry("Cooking Session", "Kitchen energy", "vibe", "cooking music playlist", ["cooking"]),
  entry("House Party", "Room full of people moving", "vibe", "house party playlist", ["party"]),
  entry("Pre-Game", "Before the night begins", "vibe", "pregame playlist", ["pregame", "party"]),
  entry("After Party", "The wind-down after the peak", "vibe", "after party playlist", ["after party"]),
  entry("Sunday Brunch", "Late start, good company", "vibe", "sunday brunch playlist", ["brunch", "sunday"]),
  entry("Beach Day", "Sand, sun, easy sound", "vibe", "beach day playlist", ["beach", "summer"]),
  entry("Pool Party", "Warm water, louder sound", "vibe", "pool party playlist", ["pool", "summer"]),
  entry("Hiking Trail", "Outdoor rhythm and stride", "vibe", "hiking outdoor playlist", ["hiking", "outdoor"]),
  entry("Camping Fire", "Acoustic under open sky", "vibe", "camping acoustic playlist", ["camping", "acoustic"]),
  entry("Gaming Session", "Immersion and reaction time", "vibe", "gaming music playlist", ["gaming"]),
  entry("Night Gaming", "Late session, locked in", "vibe", "late night gaming playlist", ["gaming", "night"]),
  entry("Shower Bangers", "Hits that hit harder wet", "vibe", "shower songs playlist", ["shower", "fun"]),
  entry("Work From Home", "Productive domestic energy", "vibe", "work from home playlist", ["work", "focus"]),
  entry("Bedtime", "Ease into sleep", "vibe", "bedtime sleep songs playlist", ["sleep", "bedtime"]),
  entry("Power Nap", "Twenty minutes of reset", "vibe", "power nap relaxing playlist", ["nap", "relaxing"]),
];

// ─── Scenes & Vibes ───────────────────────────────────────────────────────────

const SCENES: CatalogEntry[] = [
  entry("Rainy Day In", "Grey outside, warm inside", "vibe", "rainy day indoor playlist", ["rainy", "cozy"]),
  entry("Winter Fireplace", "Log crackling, soft sound", "vibe", "winter cozy fireplace playlist", ["winter", "cozy"]),
  entry("Coffee Shop", "Background hum of productivity", "vibe", "coffee shop music playlist", ["coffee shop"]),
  entry("Library Mode", "Quiet focus, no lyrics needed", "vibe", "library study instrumental playlist", ["library", "quiet"]),
  entry("Golden Hour", "That perfect light and feeling", "vibe", "golden hour sunset playlist", ["golden hour", "sunset"]),
  entry("Sunset Session", "Day closing, volume rising", "vibe", "sunset songs playlist", ["sunset"]),
  entry("City After Dark", "Neon, pavement, late hours", "vibe", "city night playlist", ["city", "night"]),
  entry("After Midnight", "The real late-night crowd", "vibe", "after midnight playlist", ["midnight", "late night"]),
  entry("Friday Night", "Permission to let go", "vibe", "friday night playlist", ["friday", "night out"]),
  entry("Saturday Morning", "Slow wake, no agenda", "vibe", "saturday morning playlist", ["saturday", "morning"]),
  entry("Weekend Energy", "Two days of freedom", "vibe", "weekend vibes playlist", ["weekend"]),
  entry("Rooftop Session", "Open sky, good company", "vibe", "rooftop party playlist", ["rooftop"]),
  entry("Hotel Room", "Anywhere, detached, floating", "vibe", "hotel room songs playlist", ["hotel", "travel"]),
  entry("Train Journey", "Motion and landscape blur", "vibe", "train journey playlist", ["train", "travel"]),
  entry("Summer Night", "Warm air, fireflies", "vibe", "summer night playlist", ["summer", "night"]),
  entry("Late Summer", "Dying warmth, back-to-school ache", "vibe", "late summer songs playlist", ["late summer"]),
  entry("Autumn Leaves", "Cooling air, changing color", "vibe", "autumn fall playlist", ["autumn", "fall"]),
  entry("Winter Nights", "Cold outside, inside warmth", "vibe", "winter night songs playlist", ["winter"]),
  entry("Spring Awakening", "New energy, new light", "vibe", "spring songs playlist", ["spring"]),
  entry("Midnight Garden", "Quiet dark, gentle grow", "vibe", "midnight garden songs playlist", ["midnight", "peaceful"]),
  entry("Desert Highway", "Vast and silent speed", "vibe", "desert highway driving playlist", ["desert", "driving"]),
  entry("Ocean Drive", "Salt air and horizon", "vibe", "ocean drive coastal playlist", ["ocean", "coast"]),
  entry("Forest Walk", "Birdsong and footsteps", "vibe", "forest walk nature playlist", ["forest", "nature"]),
  entry("Urban Jungle", "Concrete rhythm and pace", "vibe", "urban city songs playlist", ["urban", "city"]),
  entry("Late Night Bar", "Last call atmosphere", "vibe", "late night bar songs playlist", ["bar", "late night"]),
  entry("House Show", "Living room and basement gigs", "vibe", "house show indie playlist", ["indie", "intimate"]),
  entry("Record Store", "The eternal flip and discover", "vibe", "record store vibes playlist", ["vinyl", "indie"]),
  entry("Back Seat Window", "Motion and watching", "vibe", "back seat window songs playlist", ["travel", "dreamy"]),
  entry("Empty Stadium", "Anthem in the echo", "vibe", "stadium anthems playlist", ["anthems", "epic"]),
  entry("Neon Nights", "Candy-colored darkness", "vibe", "neon night songs playlist", ["neon", "night"]),
];

// ─── Regional / Scene ─────────────────────────────────────────────────────────

const REGIONAL: CatalogEntry[] = [
  entry("NYC Underground", "Brooklyn and Manhattan after hours", "vibe", "new york city music playlist", ["nyc", "new york"]),
  entry("LA Vibes", "West Coast sun and sprawl", "vibe", "los angeles music playlist", ["la", "los angeles"]),
  entry("Chicago Sound", "Blues, house, and wind", "vibe", "chicago music playlist", ["chicago"]),
  entry("Detroit Techno", "Factory rhythm, industrial soul", "genre", "detroit techno playlist", ["detroit", "techno"]),
  entry("London Sound", "From Bowie to grime", "vibe", "london music playlist", ["london", "uk"]),
  entry("Berlin Electronic", "Club Berghain and beyond", "genre", "berlin electronic playlist", ["berlin", "techno"]),
  entry("Paris Cafe", "Chanson and café jazz", "vibe", "paris cafe music playlist", ["paris", "french"]),
  entry("French Electronic", "Daft Punk and Air legacy", "genre", "french electronic playlist", ["french electronic"]),
  entry("Tokyo City Pop", "Bubble-era Japanese glamour", "genre", "tokyo city pop playlist", ["tokyo", "city pop"]),
  entry("Seoul Indie", "Han River coffee shop sound", "vibe", "seoul indie kpop playlist", ["seoul", "korean"]),
  entry("Lagos Afrobeats", "West African export", "genre", "lagos afrobeats playlist", ["lagos", "afrobeats"]),
  entry("Johannesburg Amapiano", "Log drum from Soweto", "genre", "johannesburg amapiano playlist", ["johannesburg", "amapiano"]),
  entry("Rio Bossa Nova", "Copacabana sway", "genre", "rio bossa nova playlist", ["rio", "brazil"]),
  entry("Kingston Reggae", "Root and riddim", "genre", "kingston reggae playlist", ["kingston", "jamaica"]),
  entry("Havana Salsa", "Cuban heat and brass", "genre", "havana salsa playlist", ["havana", "cuba"]),
  entry("Nordic Noir", "Icelandic post-rock and Scandinavian cold", "vibe", "nordic noir playlist", ["nordic", "scandinavia"]),
  entry("Australian Indie", "Sun-bleached and unpretentious", "genre", "australian indie playlist", ["australian", "indie"]),
  entry("UK Bass", "From dubstep to grime to UKG", "genre", "uk bass music playlist", ["uk bass"]),
  entry("Glasgow Sound", "Post-punk and shoegaze", "vibe", "glasgow indie playlist", ["glasgow", "uk indie"]),
  entry("Manchester Anthems", "Madchester to now", "vibe", "manchester music playlist", ["manchester", "uk"]),
];

// ─── Special Collections ──────────────────────────────────────────────────────

const SPECIAL: CatalogEntry[] = [
  entry("Midnight Roadtrip", "Driving away from everything", "vibe", "midnight road trip playlist", ["midnight", "drive"]),
  entry("Window Seat", "Watching the world move by", "vibe", "window seat songs playlist", ["travel", "reflective"]),
  entry("90s HipHop", "Boom bap from the golden age", "genre", "90s hip hop essentials", ["90s", "hip hop"]),
  entry("Blog Era Indie", "2007-2012 blog-rock canon", "era", "blog era indie playlist", ["blog era", "indie"]),
  entry("Velvet Weather", "Grey sky, warm room", "vibe", "velvet weather chill playlist", ["chill", "cozy"]),
  entry("Soft Landing", "Gentle transition", "vibe", "soft landing chill playlist", ["soft", "gentle"]),
  entry("Moonlit Disco", "After the club, after midnight", "vibe", "moonlit disco playlist", ["disco", "late night"]),
  entry("Soul Revival", "Neo-soul and classic soul together", "genre", "soul revival playlist", ["soul", "neo soul"]),
  entry("Jazz House", "Jazz chords, club tempo", "genre", "jazz house playlist", ["jazz", "house"]),
  entry("Piano Bar", "Keys and cocktails", "vibe", "piano bar songs playlist", ["piano", "jazz"]),
  entry("Late Night Radio", "3am dial-in frequency", "vibe", "late night radio songs playlist", ["late night"]),
  entry("Heartbreak Classics", "The greatest songs about loss", "mood", "heartbreak classic songs playlist", ["heartbreak", "classic"]),
  entry("Summer Anthems", "Peak season, peak volume", "vibe", "summer anthems playlist", ["summer", "anthems"]),
  entry("Driving Anthems", "Motorway volume and motion", "vibe", "driving anthems playlist", ["driving", "anthems"]),
  entry("Workout Anthems", "The tracks that make you push", "vibe", "workout anthems playlist", ["workout", "anthems"]),
  entry("Karaoke Classics", "Know every word", "vibe", "karaoke songs playlist", ["karaoke"]),
  entry("One-Hit Wonders", "That one perfect moment", "vibe", "one hit wonders playlist", ["one hit wonder"]),
  entry("Deep Cuts", "Beneath the surface of every genre", "vibe", "deep cuts underrated songs playlist", ["deep cuts"]),
  entry("Guilty Pleasures", "Judgement-free listening", "vibe", "guilty pleasure songs playlist", ["guilty pleasure"]),
  entry("90s R&B", "Slow jams and harmony groups", "era", "90s r&b playlist", ["90s r&b"]),
  entry("2000s Emo", "Eyeliner and catharsis", "era", "2000s emo playlist", ["emo", "2000s"]),
  entry("60s Soul", "Motown and Stax forever", "era", "60s soul playlist", ["60s soul"]),
  entry("80s New Wave", "Cold synths and angular cool", "era", "80s new wave playlist", ["80s new wave"]),
  entry("Garage Bands", "Scrappy, raw, real", "genre", "garage bands rock playlist", ["garage rock"]),
  entry("Post-Punk Wire", "Tension and abstraction", "genre", "post punk essentials playlist", ["post punk"]),
  entry("Bossa Nights", "Brazilian soft-lit sway", "genre", "bossa nova nights playlist", ["bossa nova"]),
  entry("Afro House", "Percussive elevation", "genre", "afro house playlist", ["afro house"]),
  entry("Shoegaze Signals", "Reverb wall transmissions", "genre", "shoegaze essentials playlist", ["shoegaze"]),
  entry("Ambient Drift", "Pure atmosphere, no destination", "genre", "ambient drift playlist", ["ambient"]),
  entry("Trip-Hop", "Bristol bass and broken beats", "genre", "trip hop playlist", ["trip hop"]),
  entry("Darkwave", "Gothic electronics and cold synths", "genre", "darkwave playlist", ["darkwave"]),
  entry("Lo-Fi Beats", "Dusty loops for work and study", "genre", "lofi beats study playlist", ["lofi"]),
  entry("Jungle", "Amen breaks at speed", "genre", "jungle music playlist", ["jungle", "rave"]),
];

// ─── Export ───────────────────────────────────────────────────────────────────

function dedupe(entries: CatalogEntry[]): CatalogEntry[] {
  const seen = new Set<string>();
  return entries.filter((e) => {
    if (seen.has(e.slug)) return false;
    seen.add(e.slug);
    return true;
  });
}

export const GENERATED_CATALOG: CatalogEntry[] = dedupe([
  ...MOODS,
  ...GENRES,
  ...ERAS,
  ...ACTIVITIES,
  ...SCENES,
  ...REGIONAL,
  ...SPECIAL,
]);
